### PR TITLE
Replace legacy esoleaderboards api calls with new calls

### PR DESCRIPTION
**Pull request by Woeler**
Since I completely rewrote the core of the system, the old api has been legacy for a while and is now deprecated. It will be removed in March. I replaced the old calls with the new ones.

I see I can merge, but I'll let you do that.

### CODE REVIEW

**Comment by Woeler** [comment]
https://www.esoleaderboards.com/api/score/character?megaserver=eu&characterName=Woeler&trialIdentifier=mol

https://www.esoleaderboards.com/api/score/character?megaserver=eu&accountName=Woeler&trialIdentifier=mol

**Comment by chiras** [comment]
Yes @Woeler, that "characc" is the differentiation between whether called for account or character. 

`
var characc = "Account";
	var nameorg = "";
	
	if (options.accounts.length > 0){
		nameorg = "@" + options.accounts[0].replace(/\$/g, "")		
	}else{
		nameorg = options.others.join(" ");
		if (!nameorg.startsWith("@")) characc = "Character";
	}
`

here the differentiation is made. Thanks a lot!

**Comment by Woeler** [comment]
@chiras Please check with the latest commit

**Comment by Woeler** [comment]
Making the repo public broke this pr. New one here https://github.com/chiras/foxbot/pull/6

**Pull request closed without merging**
